"""new column added

Revision ID: 0105c5cd741c
Revises: cf531c9143bd
Create Date: 2025-05-05 21:33:49.189203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0105c5cd741c'
down_revision: Union[str, None] = 'cf531c9143bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verify', sa.Column('otp_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verify', 'otp_time')
    # ### end Alembic commands ###
